export const GET_PUBLIC_RECIPES = 'GET_PUBLIC_RECIPES';
export const CLEAR_RECIPES = 'CLEAR_RECIPES';
export const ADD_RECIPE = 'ADD_RECIPE';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const CLEAR_RECIPE = 'CLEAR_RECIPE';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';
export const FILTER_RECIPES = 'FILTER_RECIPES';
export const CLEAR_FILTER = 'CLEAR_FILTER';
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAIL = 'REGISTRATION_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const AUTH_ERROR = 'AUTH_ERROR';



